"""empty message

Revision ID: 14cc99cd41ee
Revises: 
Create Date: 2023-02-12 15:23:15.799919

"""
import sqlalchemy as sa
from alembic import op
from passlib.hash import pbkdf2_sha256

# revision identifiers, used by Alembic.
revision = '14cc99cd41ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    product_table =  op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    user_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(precision=2), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(user_table,
        [
            {'email':'games@email.com','password':pbkdf2_sha256.hash('ga23mes#2002')},
        ]
    )

    op.bulk_insert(product_table,
        [
            {
                "name": "Super Mario Odyssey",
                "price": 197.88,
                "score": 100,
                "image": "super-mario-odyssey.png"
            },
            {
                "name": "Call Of Duty Infinite Warfare",
                "price": 49.99,
                "score": 80,
                "image": "call-of-duty-infinite-warfare.png"
            },
            {
                "name": "The Witcher III Wild Hunt",
                "price": 119.5,
                "score": 250,
                "image": "the-witcher-iii-wild-hunt.png"
            },
            {
                "name": "Call Of Duty WWII",
                "price": 249.99,
                "score": 205,
                "image": "call-of-duty-wwii.png"
            },
            {
                "name": "Mortal Kombat XL",
                "price": 69.99,
                "score": 150,
                "image": "mortal-kombat-xl.png"
            },
            {
                "name": "Shards of Darkness",
                "price": 71.94,
                "score": 400,
                "image": "shards-of-darkness.png"
            },
            {
                "name": "Terra Média: Sombras de Mordor",
                "price": 79.99,
                "score": 50,
                "image": "terra-media-sombras-de-mordor.png"
            },
            {
                "name": "FIFA 18",
                "price": 195.39,
                "score": 325,
                "image": "fifa-18.png"
            },
            {
                "name": "Horizon Zero Dawn",
                "price": 115.8,
                "score": 290,
                "image": "horizon-zero-dawn.png"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
